services:
    database:
        image: postgres:17-alpine
        env_file:
            - database/.env
        volumes:
            - database-data:/var/lib/postgresql/data
    server:
        build:
            context: server
            dockerfile: Dockerfile
        env_file:
            - server/.env
        depends_on:
            - database
    client:
        build:
            context: client
            dockerfile: Dockerfile
        volumes:
            - client-build:/app/build
    proxy:
        build:
            context: proxy
            dockerfile: Dockerfile
        volumes:
            - client-build:/app/client
        ports:
            - 127.0.0.1:${PUBLIC_PORT}:80
    monitoring:
        image: nicolargo/glances:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - 'GLANCES_OPT=-w'
        ports:
            - 127.0.0.1:61208:61208
volumes:
    client-build:
    database-data:
