services:
    database:
        image: postgres:17-alpine
        env_file:
            - database/.env
    server:
        build:
            context: server
            dockerfile: Dockerfile
        env_file:
            - server/.env
        depends_on:
            - database
    proxy:
        build:
            context: proxy
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:${PUBLIC_PORT}:80
