name: Deploy to production
on:
    repository_dispatch:
        types:
            - trigger_build
    push:
        branches:
            - main
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone/pull the repository and start/restart Docker
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      if cd nestjs-react; then git pull; else git clone ${{ github.repositoryUrl }} nestjs-react; fi
                      docker compose down
                      docker compose up --build --detach
