name: Deploy to production
on:
    repository_dispatch:
        types:
            - trigger_build
    push:
        branches:
            - main
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone/pull the repository and start/restart Docker
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                    rm -rf nestjs-react
                    git clone https://${{ secrets.GITHUB_TOKEN }}}@github.com/${{ github.repository }}.git nestjs-react
                    cd nestjs-react
                    sudo docker compose stop
                    sudo docker compose up --build --detach
